### PR TITLE
Fix ssh service name on handler

### LINKED ISSUE #92: SSH service not restarting
After running the `bootstrap` task the expected behavior if that the `root` user can't login using ssh, but this is not happening.

There seems to be a [bug in the handler](https://github.com/stackbuilders/sb-debian-base/blob/master/handlers/main.yml#L4), instead of `sshd` it is using `ssh` as the name of the service, which is causing the deamon not to be restarted.

### PR DESCRIPTION
**Pull request by 00dav00**
Closes #92

### CODE REVIEW

**Comment by goetzc** [comment]
Thanks David. I think this change is not needed, although the daemon is called `sshd`, the actual service is called `ssh`, as it can be seen on the following links:

https://packages.ubuntu.com/trusty/amd64/openssh-server/filelist
https://packages.ubuntu.com/xenial/amd64/openssh-server/filelist
https://packages.debian.org/jessie/amd64/openssh-server/filelist
https://packages.debian.org/stretch/amd64/openssh-server/filelist

And `sshd` is just an alias:
`Alias=sshd.service`

**Comment by 00dav00** [comment]
Just tried it and it is not working, that's why I created the pull request. The service is not restarted and you can still login as root via ssh.

**Comment by 00dav00** [comment]
I think that is worth saying that it fails silently, that's why the CI was not showing any errors during execution.

**Comment by 00dav00** [comment]
@goetzc @lpaulmp  Now the handlers are executed right after the ssh config is changed. WDYT?
screen shot 2017-10-31 at 9 58 25 am

**Comment by goetzc** [comment]
Oh, all called handlers are being run. Maybe then just run an explicit sshd restart task?

**Pull request merged**
